# Generated by Django 4.0.4 on 2022-06-28 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('type', models.CharField(choices=[('SON', 'Ultrasonic'), ('GAS', 'Gassensor'), ('LIGHT', 'Lightsensor'), ('HUM', 'HumiditySensor')], max_length=5)),
                ('reference', models.CharField(max_length=150)),
                ('data', models.TextField(max_length=1500)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
